### ISSUE TITLE
Ejemplo "CLASIFICAR COLOR"

### ISSUE THREAD

**Issue by victorsanchis** [luisllamasbinaburo/Arduino-ColorConverter#1]
Hola Luis,

He copiado tu ejemplo publicado en _luisllamas.es/arduino-sensor-color-rgb-tcs34725/_
"CLASIFICAR COLORES
En el segundo ejemplo, vamos a leer los valores RGB e intentar determinar el color que estamos leyendo. Para que sea más sencillo convertimos los valores RGB a HSV con la librería ColorConverter.
Para determinar el color empleamos el Hue del color medido. Para un ajuste fino será necesario calibrar el sensor ensayando colores y ajustando los valores de los condicionales..."

Pero, al pegar y compilar, me da contínuamente el siguiente error (por tanto llegar a cargarlo):

C:\Users\Coolmi\Documents\Arduino\libraries\Arduino-ColorConverter\src\ColorConverterLib.cpp: In static member function 'static void ColorConverter::RgbToHsv(byte, byte, byte, double&, double&, double&)':

C:\Users\Coolmi\Documents\Arduino\libraries\Arduino-ColorConverter\src\ColorConverterLib.cpp:41:9: error: 'h' may be used uninitialized in this function [-Werror=maybe-uninitialized]

   h /= 6;

         ^

C:\Users\Coolmi\Documents\Arduino\libraries\Arduino-ColorConverter\src\ColorConverterLib.cpp: In static member function 'static void ColorConverter::RgbToHsl(byte, byte, byte, double&, double&, double&)':

C:\Users\Coolmi\Documents\Arduino\libraries\Arduino-ColorConverter\src\ColorConverterLib.cpp:80:9: error: 'h' may be used uninitialized in this function [-Werror=maybe-uninitialized]

   h /= 6;

         ^

C:\Users\Coolmi\Documents\Arduino\libraries\Arduino-ColorConverter\src\ColorConverterLib.cpp: In static member function 'static void ColorConverter::HsvToRgb(double, double, double, uint8_t&, uint8_t&, uint8_t&)':

C:\Users\Coolmi\Documents\Arduino\libraries\Arduino-ColorConverter\src\ColorConverterLib.cpp:116:11: error: 'b' may be used uninitialized in this function [-Werror=maybe-uninitialized]

  blue = b * 255;

           ^

C:\Users\Coolmi\Documents\Arduino\libraries\Arduino-ColorConverter\src\ColorConverterLib.cpp:115:12: error: 'g' may be used uninitialized in this function [-Werror=maybe-uninitialized]

  green = g * 255;

            ^

C:\Users\Coolmi\Documents\Arduino\libraries\Arduino-ColorConverter\src\ColorConverterLib.cpp:114:10: error: 'r' may be used uninitialized in this function [-Werror=maybe-uninitialized]

  red = r * 255;

          ^

cc1plus.exe: some warnings being treated as errors

Lo he intentado varias veces, pero siempre detecta esos "errores"... ¿hay algo que se me haya pasado?
Gracias de antemano!

Víctor

**Comment by luisllamasbinaburo** [comment]
No he podido reproducir el error.
