### ISSUE TITLE
not working: RGBConverterLib.h: No such file or directory

### ISSUE THREAD

**Issue by in23o** [luisllamasbinaburo/Arduino-ColorConverter#2]
Hola Luis, 

puedes revisar el LIB porque no puedo subir al Nano.
Pienso que algo has cambiado en el codigo?

Gracias!
Henry

**Comment by luisllamasbinaburo** [comment]
Se ha cambiado el nombre de RGBConverter a ColorConverter, y me deje un cambio. 
Arreglado, gracias
