### ISSUE TITLE
not working: RGBConverterLib.h: No such file or directory

### ISSUE THREAD

**Issue by awgrover** [luisllamasbinaburo/Arduino-ColorConverter#3]
cf. #2 

Pardon that I only speak English.

The Arduino IDE, Library Manager, is installing the wrong set of files. It says 1.1, but

```
/home/awgrover/Arduino/libraries/ColorConverter/src/ColorConverterLib.cpp:10:10: fatal error: RGBConverterLib.h: No such file or directory
 #include "RGBConverterLib.h"
```

**Comment by ModuloFS** [comment]
Hello,

i have the same problem at Platformio IDE!

**Comment by n0xxa** [comment]
the library name was changed, use #include "ColorConverterLib.h"

**Comment by luisllamasbinaburo** [comment]
Update readme. Thanks @n0xxa
