### ISSUE TITLE
Problem with the Library Source Files

### ISSUE THREAD

**Issue by italo-coelho** [luisllamasbinaburo/Arduino-ColorConverter#4]
[src-fix.zip](https://github.com/luisllamasbinaburo/Arduino-ColorConverter/files/6398888/src-fix.zip)

The wrong name was used for .h include on .cpp. The name of the class has been changed to RGBConverter with no notice and doesn't match the Library name.

**Comment by kabrio** [comment]
can confirm name mix up in library.
library not working as is @luisllamasbinaburo

**Comment by luisllamasbinaburo** [comment]
Code works perfectly, tested right now. Verify you have only one copy of the library in your Arduino libs folder
